### PR TITLE
Migrate mini-app compilation from esbuild to Rolldown

### PR DESCRIPTION
**Pull request by hamzamerzic**
## Summary

- replace esbuild with the stable Rolldown 1.2 API across mini-app compilation, generated runtime builds, validation, tests, and repository hooks
- preserve the single-module, offline-capable bundle contract: production React, runtime injection, supported libraries, the byte-zero ABI marker, default export validation, and no emitted assets or non-URL external imports
- fail unresolved imports, retain documented online-only URL imports, and inline supported static dynamic imports
- serialize native compiler subprocesses to bound concurrent peak memory on constrained instances, while retaining timeout and cancellation cleanup
- remove the now-unused global esbuild image install and use the locked frontend compiler for syntax checks and generated runtime verification
- fix forward by dropping Function.name/Class.name preservation; apps use explicit labels, IDs, stable keys, or displayName when semantics require a name

## Efficiency and maintenance

- generated Mobius runtime: 116,434 -> 105,718 bytes (about 9% smaller)
- no resident compiler worker and no dual esbuild/Rolldown path
- all 48 active app sources and 637 deployed source files were parsed; none rely on function/class names
- six representative deployed apps are 13.7% smaller raw in aggregate without keepNames (5.9% gzip, 4.7% Brotli); per-app raw savings are 9.3-22.5%
- Acorn remains installed at 8.18.0 while its manifest minimum stays scoped to the existing ^8.17.0 contract

## Validation

- frontend unit and hook suites: 2,420 passed; production build, lint, runtime determinism, and zero-vulnerability audit passed
- focused compiler/runtime/source/storage suites passed; latest combined compiler contract run: 83 passed
- all 29 deployed app source trees compile under the Rolldown contract
- all 23 advertised runtime import forms compile, including pdfjs-dist and lucide-react
- fresh install contains rolldown@1.2.2 and no installed esbuild package
- fresh hosted backend, frontend, privacy, and full image/browser E2E gates run on exact final head 640c58d

The sole local full-suite interruption is a pre-existing app_git portability failure reproduced unchanged on origin/main under Git 2.43; the hosted backend gate remains authoritative. A normal image rebuild is required for the compiler dependency change to reach deployments.

### CODE REVIEW

**Comment by hamzamerzic** [comment]
Closing in favor of #605. This branch was repeatedly updated with an unrelated compiler migration after the image/browser review, so the reviewed six-file image and browser cleanup now lives in the clean replacement. The compiler migration has been preserved separately for a full architecture and compatibility audit.

**Comment by hamzamerzic** [comment]
Independent fix-forward audit: the `keepNames` compatibility commit should not ship.

- Parsed all 48 active deployed app sources: 152 `.name` reads, zero resolve to function/class/component/loader bindings.
- Parsed 637 deployed source files: 488 `.name` reads, again zero function/class-name reliance.
- Exact Rolldown A/B on six deployed apps: `keepNames` adds 537,074 raw bytes total (+13.7%), +5.9% gzip, and +4.7% Brotli; individual raw overhead is 9.3–22.5%.
- The user explicitly authorized dropping backward compatibility and asked us to optimize limited-resource Railway trial usage.

Please keep commit `634b594`'s Acorn manifest scoping (it does not downgrade the installed 8.18.0), but drop/revert `072e8e8`. Explicit labels/IDs/`displayName` are the maintainable forward contract. Do not queue the current `keepNames: true` head.

**Comment by hamzamerzic** [comment]
Closing in favor of the clean reviewed replacement #609. This branch was repeatedly force-pushed back to a compatibility-breaking revision during review and even while the approved SHA was in the merge queue. #609 pins the exact independently approved Rolldown-only commit (634b5944), including name preservation and its evaluated regression, and remains Draft until its own fresh gates complete.
